sudo: false
language: php
cache:
  directories:
    - $HOME/.composer/cache
    - vendor
matrix:
  fast_finish: true
  include:
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm
before_script:
  - composer self-update
  - composer install
script:
 - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then phpunit; fi
 - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpunit --coverage-text --coverage-clover=coverage.clover; fi
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
notifications:
  email: false